### ISSUE TITLE
Enforce HTTPS for direct connections to cloudant.com

### ISSUE THREAD

**Issue by mikerhodes** [cloudant/nodejs-cloudant#2] opened 2014-08-11 19:28 UTC
While we can't support HTTPS for virtual hosts quite yet, all direct connections to Cloudant should use HTTPS. We should be careful to always use HTTPS in the URLs we generate, and should validate user-supplied URLs.

**Comment by glynnbird** [comment] 2015-06-16 12:00
The current state-of-play with this is that 

* if you instantiate the cloudant library with an object ( { account: "glynn"} ) you are forced into HTTPS communication
* if you instantiate the cloudant library with a string ( "http://glynn.cloudant.com"), you get the protocol you specified

This isn't by design, it's just the way the code paths diverge. It would be easy to force HTTPS for the second code path, but whether that's what we want is debatable.

**Comment by jhs** [comment] 2015-06-24 09:14
"If you pass in the URL, you know what you are doing."

Okay, we have some new logic if this is plaintext AND with credentials:

- For 1.1, we will warn the user, but proceed
- For 2.0, we will return an exception

In any case, with an "allowPlaintext" flag, then this behavior will be supressed.

**Comment by glynnbird** [comment] 2015-06-24 10:49
Fixed with commit https://github.com/cloudant/nodejs-cloudant/commit/50881767e5cefb2052982d7081f168c312463f66

**Closed by glynnbird** 2015-06-24 10:49 UTC
Labels: Agenda
