### ISSUE TITLE
Updating a Document

### ISSUE THREAD

**Issue by benrondeau** [cloudant/nodejs-cloudant#67] opened 2015-06-15 21:46 UTC
Is there a way to update an existing document without using ```db.copy```? Surely I must be crazy to think that the 'U' of CRUD operations is missing from this library.

**Comment by glynnbird** [comment] 2015-06-16 06:47
This is a duplicate of issue #16. The documentation doesn't show usage of the `insert` function to update a document. I'll fix that.

**Comment by glynnbird** [comment] 2015-06-16 06:59
Improved the documentation.

**Closed by glynnbird** 2015-06-16 06:59 UTC
