### ISSUE TITLE
losing connection to database

### ISSUE THREAD

**Issue by GianlucaBP** [cloudant/nodejs-cloudant#366] opened 2019-01-18 17:00 UTC
## Bug Description
I have a cloud application which uses the Cloudant nodejs library @cloudant/cloudant@3.0.2
all seems to start successfully: connection to the db and data retrieval run apparently with any issues , performance is good. 
after a variant time ( from 10 mins to 30 mins), the library stops to submit the requests to the cloudant server.

the only chance to recover is to restart the application.

also tried to re-initiate the library without restart the application but did not work.
 
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
perform db.get in a loop 
not needed to do a strict loop, also 1 request each 15 secs.

### 2. What you expected to happen
I was expecting to get the data from the db

### 3. What actually happened
seems the library  stop to submit the requests to the cloudant server
the last log is:
cloudant:client Delaying request for 0 Msecs. 

the library never comes back, once it hungs it will never rescue from that state.

from a network perspective I can't see an opened connection against the remote cloudant server (netstat does not show the link to the remote db), but if I perform a manual curl from the same server it runs.

## Environment details
 DEBUG: cloudant*,nano
 NODE_DEBUG: request,response
- Version(s) that are affected by this issue.
    > 3.0.2
- Node.js version
    > 6.16.0

Connection settings

	//retry plugin config
	var retry_cfg={ retryErrors: false, retryStatusCodes: [ 429 ] }

	//sockets
	var cloudant_agent = new http.Agent({
		keepAlive: (true or false... same issue)
		keepAliveMsecs: 30000,
		maxSockets: (varies from 10 to 100... same issue)
	});

	//cloudant connection config
	var cloudant_cfg={ 
		account:cloudant_username, 
		password:cloudant_password, 
		maxAttempt: 5, 
		plugins: { retry: retry_cfg	},
		requestDefaults: { agent: cloudant_agent } 
	}

Wondering there is some known issue on this release of the library or with the nodejs version

really appreciated any help

Gianluca

**Comment by emlaver** [comment] 2019-01-18 17:06
Hi @GianlucaBP, can you provide and logging/debugging when this issue occurs?

**Comment by GianlucaBP** [comment] 2019-01-18 17:35
@emlaver hi Esteban, sure. 
attaching.
thx
G
[logs-prod-Jan-18_filtered.txt](https://github.com/cloudant/nodejs-cloudant/files/2773931/logs-prod-Jan-18_filtered.txt)

**Comment by emlaver** [comment] 2019-01-18 17:50
@GianlucaBP Can you please provide the code you are using that throws the error below?
```
   [31m2019-01-18T17:14:04.59+0100 [APP/PROC/WEB/0] ERR 2019-01-18T16:14:04.591Z nano { method: 'GET',[0m
   [31m2019-01-18T17:14:04.59+0100 [APP/PROC/WEB/0] ERR   headers: [0m
   [31m2019-01-18T17:14:04.59+0100 [APP/PROC/WEB/0] ERR    { 'content-type': 'application/json',[0m
   [31m2019-01-18T17:14:04.59+0100 [APP/PROC/WEB/0] ERR      accept: 'application/json' },[0m
   [31m2019-01-18T17:14:04.59+0100 [APP/PROC/WEB/0] ERR   uri: 'https://<user>:<pwd>@<user>.cloudant.com/mydb/CONFIG-SERVER-PORTAL' }[0m
   [31m2019-01-18T17:14:04.59+0100 [APP/PROC/WEB/0] ERR 2019-01-18T16:14:04.595Z cloudant:client Request attempt: 1[0m
   [31m2019-01-18T17:14:04.60+0100 [APP/PROC/WEB/0] ERR 2019-01-18T16:14:04.596Z cloudant:clientutils Running hook onRequest for plugin 'retry'.[0m
   [31m2019-01-18T17:14:04.60+0100 [APP/PROC/WEB/0] ERR 2019-01-18T16:14:04.600Z cloudant:client Delaying request for 0 Msecs.[0m
```
Also, what `nano` and `request` version are you using?

**Comment by GianlucaBP** [comment] 2019-01-18 22:03
@emlaver : that logs come from the nodejs cloudant library, and it is not a real ERRor , it is only a trace. 
i.e. : the log row "client Delaying request for 0 Msecs" comes from line 311 of https://github.com/cloudant/nodejs-cloudant/blob/master/lib/client.js 
those lines are printed-out each time a database request is submitted through the nodejs cloudant library, and the DEBUG is on.
When we are in front of the issue, that line is the last one printed-out in the log.
When the library submits the request to the cloudant server , some other lines are printed-out starting from "client Submitting request" and the complete url of the request is shown.
I'm attaching a file with a complete transaction (see the same log at line 8 followed by many others)

thx again
G

[complete_transaction.txt](https://github.com/cloudant/nodejs-cloudant/files/2774655/complete_transaction.txt)

**Comment by GianlucaBP** [comment] 2019-01-18 22:08
@emlaver : regarding the second question... I do not really know: the following attached file 
is all I have about the included modules .
[stage_info.txt](https://github.com/cloudant/nodejs-cloudant/files/2774679/stage_info.txt)

**Comment by ricellis** [comment] 2019-01-21 16:45
I ran the loop you described (on Node.js 6.16.0 and an 8.x) and I was not able to reproduce this issue.

It appears from the server side logs that the server is responding `200` to all your requests and in a timely fashion from when the requests are received (typically << 1 s, except for the occasional query that takes longer, but still not close to 2 min).

One thing I noticed was that there was a large difference in the timestamps from when the request is made in your attached client side log to the when the requests are being accepted on the server side. This difference did not appear to be constant so seems unlikely to be clock differences between the client and server side (both of which I expect are likely set via NTP anyway). In one case it looked like it took over 5 minutes for the request to reach the Cloudant server from your app.

If you have a proxy or some other tier between your app and Cloudant then I'd recommend looking at the performance there and seeing if that is what is holding up your requests.

**Comment by GianlucaBP** [comment] 2019-01-21 17:33
@ricellis hi Rich, thx for your investigation. 
I also made some other tests and seems the application remains up&running more time if the loop of queries is scheduled less frequently. Actually I moved the frequency from 1-per-minute to 1-per-15minutes and the app is up sine 2h+ (never happened before). I do not know what is the side fx of making less requests in the timeframe (if used memory or the timers in the setTimeout function...), for sure, I will need more throughput in therms of number of operations/sec.
The strange thing is that it has been running for an year and never had this kind of issues until the new year started. 
I will continue the investigation.
Thx

**Comment by GianlucaBP** [comment] 2019-01-24 12:02
hi, 

many thx for the investigation and feedback.

I rolled back the cron library to a previous version and from my side it seems to be better.

It was probably performing some extra submission than what was scheduled, do not really know.

I will open a case against them saying it is probably incompatible with cloudant library.

thx again for your time and effort
G

**Comment by ricellis** [comment] 2019-01-24 13:09
Thanks for the update, I'll close this issue.

**Closed by ricellis** 2019-01-24 13:09 UTC
